baseURL = "http://www.czkit.com/"
languageCode = "zh-cn"
title = "CZKit"
theme = "hyde-hyde"

[params]
    description = "Game & Golang"
    author = "CZ"
	authorimage = "/images/logo.png"
	disqusShortname = "czkit"
	highlightjs = true
	UtterancesRepo = "cz-it/czkit.com"
	UtterancesIssueTerm = "pathname"
	UtterancesTheme = "github-light"


[params.social]
	github = "cz-it"
	email="czkit_theng@163.com"

[[menu.main]]
	name = "Posts"
	weight = 100
	identifier = "posts"
	url = "/posts/"

[[menu.main]]
	name = "Category"
	weight = 200
	identifier = "categories"
	url = "/categories/"

[[menu.main]]
	name = "Tags"
	weight = 300
	identifier = "tags"
	url = "/tags/"

[[menu.main]]
	name = "About"
	identifier = "about"
	weight = 400
	url = "/about.html"
